trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    VERSION=$(docker run --rm eclipse-mosquitto /usr/sbin/mosquitto --help | grep version | awk '{print $3}')
    echo "##vso[task.setvariable variable=version]$VERSION"
  displayName: 'Read version number from container'  

- task: GitHubRelease@0
  inputs:
    gitHubConnection: github
    repositoryName: '$(Build.Repository.Name)'
    action: 'create'
    target: '$(Build.SourceVersion)'
    tagSource: 'auto'
    releaseNotesSource: 'input'
    addChangeLog: false

- task: Docker@2
  displayName: 'Build docker container'  
  inputs:
    containerRegistry: 'dockerhub'
    repository: 'dil001/mosquitto'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: |
      $(version)
      $(version).$(Build.SourceVersion)
      latest
