trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    VERSION=$(docker run --rm eclipse-mosquitto /usr/sbin/mosquitto --help | grep version | awk '{print $3}')
    echo "##vso[task.setvariable variable=version]$VERSION"
  displayName: 'Read version number from container'  

- script: |
    git tag $(version).$(Build.SourceVersion)
    git push origin $(version).$(Build.SourceVersion)
  displayName: 'Set github tag'

- task: Docker@2
  displayName: 'Build docker container'  
  inputs:
    containerRegistry: 'dockerhub'
    repository: 'dil001/mosquitto'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: |
      $(version)
      $(version).$(Build.SourceVersion)
      latest
