trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    VERSION=$(cat version.txt)
    echo "##vso[task.setvariable variable=version]$VERSION"
  displayName: 'Read version number from file'  

- task: Docker@2
  displayName: 'Build docker container'  
  inputs:
    containerRegistry: 'dil001reg'
    repository: 'mosquitto'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: |
      $(version)-$(Build.BuildId)
      latest
